environment:
    project: newsuk-datatech-dev-1251
    #dataset_input: user_models_input
    dataset_output: tnl_engagement_test
    output_table1: tnl_engagement_current
    output_table2: tnl_section_current
    output_table_gcs1: gs://newsuk-datatech-dev/data_science/tnl_engagement_current-*.csv
    output_table_gcs2: gs://newsuk-datatech-dev/data_science/tnl_section_current-*.csv
    output_gcs_storage:  gs://newsuk-datatech-dev/data_science/




